name: pulpiprint_program
description: Administrador de escritorio profesional para PulpiPrint.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.2.1
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  supabase_flutter: ^2.8.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/

# Configuración de Iconos
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/pulpiprint_program.png" # Tu imagen
  windows:
    generate: true
    icon_size: 256 # Tamaño óptimo para Windows
  macos:
    generate: true
